"""Strict public and durable contracts for P2.8 design promotion.

Confidentiality and execution trust are deliberately separate here.  A daemon
candidate may be department-internal while its generated bytes remain
untrusted.  Only a structurally verified passive PNG can cross the comparison
rendering seam, and human candidate/release decisions remain distinct facts.
"""

from __future__ import annotations

import hashlib
import json
from typing import Annotated, Any, Literal

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StringConstraints,
    StrictBool,
    model_validator,
)


Sha256 = Annotated[str, StringConstraints(pattern=r"^[a-f0-9]{64}$")]
RequestId = Annotated[str, StringConstraints(pattern=r"^req_[a-f0-9]{32}$")]
CandidateId = Annotated[str, StringConstraints(pattern=r"^odc-[a-f0-9]{32}$")]
ReasonCode = Literal[
    "visual_mismatch",
    "trust_semantics",
    "accessibility",
    "incomplete_matrix",
    "other",
]


class StrictModel(BaseModel):
    model_config = ConfigDict(extra="forbid", strict=True)


class ExpectedTarget(StrictModel):
    kind: Literal["present", "absent"]
    sha256: Sha256 | None = None

    @model_validator(mode="after")
    def _validate_shape(self) -> "ExpectedTarget":
        if self.kind == "present" and self.sha256 is None:
            raise ValueError("present target requires sha256")
        if self.kind == "absent" and self.sha256 is not None:
            raise ValueError("absent target forbids sha256")
        return self


class ComparisonCreate(StrictModel):
    request_id: RequestId
    task_id: Annotated[str, StringConstraints(min_length=1, max_length=160)]


class SelectionRequest(StrictModel):
    request_id: RequestId
    action: Literal["approve", "reject"]
    expected_comparison_sha256: Sha256
    candidate_id: CandidateId | None
    reason_code: ReasonCode | None
    comment: Annotated[str, StringConstraints(max_length=2000)] | None = None

    @model_validator(mode="after")
    def _validate_decision(self) -> "SelectionRequest":
        if self.action == "approve":
            if self.candidate_id is None:
                raise ValueError("candidate approval requires candidate_id")
            if self.reason_code is not None:
                raise ValueError("candidate approval forbids rejection reason")
        else:
            if self.candidate_id is not None:
                raise ValueError("candidate rejection forbids candidate_id")
            if self.reason_code is None:
                raise ValueError("candidate rejection requires reason_code")
        if self.reason_code == "other" and (
            self.comment is None or not self.comment.strip()
        ):
            raise ValueError("reason_code other requires a nonblank comment")
        return self


class ReleaseRequestCreate(StrictModel):
    request_id: RequestId
    selection_id: Annotated[str, StringConstraints(pattern=r"^selection_[a-f0-9]{32}$")]
    expected_comparison_sha256: Sha256
    expected_candidate_sha256: Sha256
    expected_target: ExpectedTarget


class ReleaseDecisionRequest(StrictModel):
    request_id: RequestId
    action: Literal["approve", "reject"]
    expected_summary_sha256: Sha256
    reason_code: ReasonCode | None
    comment: Annotated[str, StringConstraints(max_length=2000)] | None = None

    @model_validator(mode="after")
    def _validate_decision(self) -> "ReleaseDecisionRequest":
        if self.action == "approve" and self.reason_code is not None:
            raise ValueError("release approval forbids rejection reason")
        if self.action == "reject" and self.reason_code is None:
            raise ValueError("release rejection requires reason_code")
        if self.reason_code == "other" and (
            self.comment is None or not self.comment.strip()
        ):
            raise ValueError("reason_code other requires a nonblank comment")
        return self


class PublishRequest(StrictModel):
    request_id: RequestId
    expected_release_package_sha256: Sha256
    expected_target: ExpectedTarget
    confirm: StrictBool

    @model_validator(mode="after")
    def _confirm_exactly_true(self) -> "PublishRequest":
        if self.confirm is not True:
            raise ValueError("publish confirmation must be literal true")
        return self


class RollbackRequest(StrictModel):
    request_id: RequestId
    expected_release_package_sha256: Sha256
    expected_current_sha256: Sha256
    confirm: StrictBool

    @model_validator(mode="after")
    def _confirm_exactly_true(self) -> "RollbackRequest":
        if self.confirm is not True:
            raise ValueError("rollback confirmation must be literal true")
        return self


class Actor(StrictModel):
    username: Annotated[str, StringConstraints(min_length=1, max_length=128)]
    display_name: Annotated[str, StringConstraints(min_length=1, max_length=256)]


class Viewport(StrictModel):
    width: Annotated[int, Field(ge=1, le=4096)]
    height: Annotated[int, Field(ge=1, le=4096)]
    dpr: Annotated[int, Field(ge=1, le=4)]


class CapturedCandidateFile(StrictModel):
    source_path: Annotated[str, StringConstraints(min_length=1, max_length=240)]
    bundle_relpath: Annotated[str, StringConstraints(min_length=1, max_length=240)]
    media_type: Annotated[str, StringConstraints(min_length=1, max_length=100)]
    size_bytes: Annotated[int, Field(ge=1, le=4 * 1024 * 1024)]
    sha256: Sha256
    role: Literal["candidate_source", "passive_preview"]


class CandidateSourceRef(StrictModel):
    path: Annotated[str, StringConstraints(min_length=1, max_length=240)]
    sha256: Sha256


class CandidateImageRef(CandidateSourceRef):
    size_bytes: Annotated[int, Field(ge=1, le=4 * 1024 * 1024)]
    media_type: Literal["image/png"]
    width: Annotated[int, Field(ge=1, le=4096)]
    height: Annotated[int, Field(ge=1, le=4096)]


class PromotableAsset(StrictModel):
    slot_id: Literal["default_desktop_light"]
    source_path: Annotated[str, StringConstraints(min_length=1, max_length=240)]
    bundle_relpath: Annotated[str, StringConstraints(min_length=1, max_length=240)]
    media_type: Literal["image/png"]
    size_bytes: Annotated[int, Field(ge=1, le=4 * 1024 * 1024)]
    sha256: Sha256


class PassivePreviewScan(StrictModel):
    policy: Literal["flai-passive-png/v1"]
    passed: Literal[True]
    active_content_executed: Literal[False]


class PassivePreview(StrictModel):
    slot_id: Annotated[str, StringConstraints(min_length=1, max_length=128)]
    viewport: Viewport
    state: Annotated[str, StringConstraints(min_length=1, max_length=64)]
    theme: Literal["light", "dark"]
    locale: Annotated[str, StringConstraints(min_length=1, max_length=32)]
    source: CandidateSourceRef
    image: CandidateImageRef
    passive_preview_scan: PassivePreviewScan

    @property
    def matrix_key(self) -> tuple[object, ...]:
        return (
            self.slot_id,
            self.viewport.width,
            self.viewport.height,
            self.viewport.dpr,
            self.state,
            self.theme,
            self.locale,
        )


class OpenDesignCandidateManifest(StrictModel):
    schema_version: Literal["open-design-daemon-candidate-manifest/v1"]
    review_contract: Literal["open-design-candidate/v1"]
    generator_kind: Literal["open_design_daemon"]
    classification: Literal["sensitive"]
    candidate_id: CandidateId
    asset_slot: Annotated[str, StringConstraints(min_length=1, max_length=128)]
    execution_trust: Literal["untrusted_generated"]
    production_readiness: Literal["trial_not_attested"]
    candidate_only: Literal[True]
    release_effect: Literal["none"]
    mock: Literal[False]
    project_id: Annotated[str, StringConstraints(min_length=1, max_length=160)]
    run_id: Annotated[str, StringConstraints(min_length=1, max_length=160)]
    result_package_sha256: Sha256
    design_reference_package_sha256: Sha256
    file_set_sha256: Sha256
    captured_files: Annotated[list[CapturedCandidateFile], Field(min_length=2, max_length=32)]
    passive_previews: Annotated[list[PassivePreview], Field(min_length=1, max_length=16)]
    promotable_asset: PromotableAsset

    @model_validator(mode="after")
    def _validate_manifest_graph(self) -> "OpenDesignCandidateManifest":
        captured_by_path: dict[str, CapturedCandidateFile] = {}
        bundle_paths: set[str] = set()
        for captured in self.captured_files:
            folded_source = captured.source_path.casefold()
            folded_bundle = captured.bundle_relpath.casefold()
            if folded_source in captured_by_path or folded_bundle in bundle_paths:
                raise ValueError("captured candidate paths must be unique case-insensitively")
            captured_by_path[folded_source] = captured
            bundle_paths.add(folded_bundle)
        sources = [item for item in self.captured_files if item.role == "candidate_source"]
        if not sources:
            raise ValueError("candidate manifest requires at least one raw source")
        matrix_keys: set[tuple[object, ...]] = set()
        for preview in self.passive_previews:
            if preview.matrix_key in matrix_keys:
                raise ValueError("passive preview matrix entries must be unique")
            matrix_keys.add(preview.matrix_key)
            source_record = captured_by_path.get(preview.source.path.casefold())
            image_record = captured_by_path.get(preview.image.path.casefold())
            if (
                source_record is None
                or source_record.role != "candidate_source"
                or source_record.sha256 != preview.source.sha256
                or source_record.source_path != preview.source.path
            ):
                raise ValueError("preview source is not the exact candidate source")
            if (
                image_record is None
                or image_record.role != "passive_preview"
                or image_record.source_path != preview.image.path
                or image_record.sha256 != preview.image.sha256
                or image_record.size_bytes != preview.image.size_bytes
                or image_record.media_type != preview.image.media_type
            ):
                raise ValueError("preview image is not the exact captured PNG")
        promoted_captured = [
            item
            for item in self.captured_files
            if item.source_path == self.promotable_asset.source_path
            and item.bundle_relpath == self.promotable_asset.bundle_relpath
            and item.media_type == self.promotable_asset.media_type
            and item.size_bytes == self.promotable_asset.size_bytes
            and item.sha256 == self.promotable_asset.sha256
            and item.role == "passive_preview"
        ]
        promoted_previews = [
            item
            for item in self.passive_previews
            if item.slot_id == self.promotable_asset.slot_id
            and item.image.path == self.promotable_asset.source_path
            and item.image.media_type == self.promotable_asset.media_type
            and item.image.size_bytes == self.promotable_asset.size_bytes
            and item.image.sha256 == self.promotable_asset.sha256
        ]
        if len(promoted_captured) != 1 or len(promoted_previews) != 1:
            raise ValueError(
                "promotable_asset must bind one exact captured passive preview"
            )
        return self


def canonical_json_bytes(value: Any) -> bytes:
    """Return the sole byte representation used for P2.8 hashes and replay."""

    return json.dumps(
        value,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
        allow_nan=False,
    ).encode("utf-8")


def canonical_sha256(value: Any) -> str:
    return hashlib.sha256(canonical_json_bytes(value)).hexdigest()
