"""Passive candidate policy: closed text allowlist plus structurally checked PNG."""

from __future__ import annotations

import json
import math
import re
import struct
import unicodedata
import zlib
from pathlib import PurePosixPath, PureWindowsPath
from typing import Iterable


class CandidatePolicyError(ValueError):
    """Generated bytes do not satisfy the passive-candidate contract."""


MAX_FILES = 32
MAX_FILE_BYTES = 4 * 1024 * 1024
MAX_TOTAL_BYTES = 8 * 1024 * 1024
MAX_PNG_WIDTH = 4096
MAX_PNG_HEIGHT = 4096
MAX_PNG_PIXELS = 10_000_000

_TEXT_TYPES = {
    ".html": "text/html",
    ".svg": "image/svg+xml",
    ".css": "text/css",
    ".json": "application/json",
    ".md": "text/markdown",
}
_PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"
_WINDOWS_RESERVED = {
    "con",
    "prn",
    "aux",
    "nul",
    *(f"com{number}" for number in range(1, 10)),
    *(f"lpt{number}" for number in range(1, 10)),
}
_DANGEROUS_TAG = re.compile(
    r"<\s*/?\s*(?:script|iframe|object|embed|applet|base|link|meta|form|foreignObject|animate|animateMotion|animateTransform|set)\b",
    re.IGNORECASE,
)
_EVENT_ATTRIBUTE = re.compile(r"\bon[a-z0-9_-]+\s*=", re.IGNORECASE)
_URL_ATTRIBUTE = re.compile(
    r"\b(?:href|src|srcset|ping|action|formaction|poster|background|cite|data|xlink:href)\s*=",
    re.IGNORECASE,
)
_HTML_ENTITY = re.compile(r"&(?:#[xX]?[0-9a-fA-F]+|[A-Za-z][A-Za-z0-9]+);")
_REMOTE_OR_EXECUTABLE_URL = re.compile(
    r"(?:https?:|data:|blob:|javascript:|file:|\\\\|(?<!:)//)",
    re.IGNORECASE,
)
_CSS_EXECUTION = re.compile(
    r"(?:@import\b|url\s*\(|expression\s*\(|behavior\s*:|-moz-binding\s*:|\\)",
    re.IGNORECASE,
)
_XML_EXECUTION = re.compile(r"<!\s*(?:DOCTYPE|ENTITY)\b", re.IGNORECASE)


def _unique_json_object(pairs: list[tuple[str, object]]) -> dict[str, object]:
    result: dict[str, object] = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f"duplicate JSON object key: {key}")
        result[key] = value
    return result


def validate_safe_path(raw_path: str) -> str:
    if not isinstance(raw_path, str) or not raw_path or "\x00" in raw_path:
        raise CandidatePolicyError("candidate path is empty or contains NUL")
    if raw_path != unicodedata.normalize("NFC", raw_path):
        raise CandidatePolicyError("candidate path must use NFC normalization")
    if len(raw_path) > 240 or "\\" in raw_path or "//" in raw_path:
        raise CandidatePolicyError("candidate path is not cross-platform safe")
    posix = PurePosixPath(raw_path)
    windows = PureWindowsPath(raw_path)
    if raw_path.endswith("/") or raw_path != posix.as_posix():
        raise CandidatePolicyError("candidate path is not in canonical POSIX form")
    if posix.is_absolute() or windows.is_absolute() or windows.drive:
        raise CandidatePolicyError("candidate path must be relative")
    if not posix.parts or any(part in {"", ".", ".."} for part in posix.parts):
        raise CandidatePolicyError("candidate path contains an unsafe segment")
    for segment in posix.parts:
        if len(segment) > 100 or segment.endswith((" ", ".")):
            raise CandidatePolicyError("candidate path contains a Windows-unsafe segment")
        if any(ord(char) < 32 or char in '<>:"|?*' for char in segment):
            raise CandidatePolicyError("candidate path contains a forbidden character")
        stem = segment.split(".", 1)[0].casefold()
        if stem in _WINDOWS_RESERVED:
            raise CandidatePolicyError("candidate path uses a Windows reserved name")
    return raw_path


def _validate_text(path: str, media_type: str, content: bytes) -> None:
    try:
        text = content.decode("utf-8", errors="strict")
    except UnicodeDecodeError as exc:
        raise CandidatePolicyError(f"{path} is not strict UTF-8") from exc
    if text.startswith("\ufeff") or "\x00" in text:
        raise CandidatePolicyError(f"{path} contains a BOM or NUL")
    if _REMOTE_OR_EXECUTABLE_URL.search(text):
        raise CandidatePolicyError(f"{path} contains a remote or executable URL")
    if _EVENT_ATTRIBUTE.search(text):
        raise CandidatePolicyError(f"{path} contains an event handler")
    if media_type in {"text/html", "image/svg+xml"} and (
        _URL_ATTRIBUTE.search(text) or _HTML_ENTITY.search(text)
    ):
        raise CandidatePolicyError(f"{path} contains an encoded or URL-bearing attribute")
    if _DANGEROUS_TAG.search(text) or _XML_EXECUTION.search(text):
        raise CandidatePolicyError(f"{path} contains active markup")
    if _CSS_EXECUTION.search(text):
        raise CandidatePolicyError(f"{path} contains active CSS")
    if media_type == "application/json":
        try:
            json.loads(
                text,
                object_pairs_hook=_unique_json_object,
                parse_constant=lambda value: (_ for _ in ()).throw(ValueError(value)),
            )
        except (json.JSONDecodeError, ValueError) as exc:
            raise CandidatePolicyError(f"{path} is not strict JSON") from exc


def validate_png(content: bytes) -> dict[str, int]:
    """Validate a bounded, single-frame, non-interlaced PNG and its zlib payload."""

    if len(content) > MAX_FILE_BYTES or not content.startswith(_PNG_SIGNATURE):
        raise CandidatePolicyError("PNG signature or size is invalid")
    offset = len(_PNG_SIGNATURE)
    chunks: list[tuple[bytes, bytes]] = []
    seen_iend = False
    while offset < len(content):
        if len(content) - offset < 12:
            raise CandidatePolicyError("PNG chunk is truncated")
        length = struct.unpack(">I", content[offset : offset + 4])[0]
        kind = content[offset + 4 : offset + 8]
        end = offset + 12 + length
        if end > len(content) or len(kind) != 4 or not all(65 <= byte <= 90 or 97 <= byte <= 122 for byte in kind):
            raise CandidatePolicyError("PNG chunk framing is invalid")
        payload = content[offset + 8 : offset + 8 + length]
        expected_crc = struct.unpack(">I", content[offset + 8 + length : end])[0]
        if zlib.crc32(kind + payload) & 0xFFFFFFFF != expected_crc:
            raise CandidatePolicyError("PNG chunk CRC mismatch")
        if seen_iend:
            raise CandidatePolicyError("PNG contains trailing bytes after IEND")
        chunks.append((kind, payload))
        if kind == b"IEND":
            seen_iend = True
        offset = end
    if not seen_iend or offset != len(content):
        raise CandidatePolicyError("PNG is missing a terminal IEND")
    if not chunks or chunks[0][0] != b"IHDR" or chunks[-1] != (b"IEND", b""):
        raise CandidatePolicyError("PNG IHDR/IEND ordering is invalid")
    if sum(kind == b"IHDR" for kind, _ in chunks) != 1:
        raise CandidatePolicyError("PNG must contain exactly one IHDR")

    ihdr = chunks[0][1]
    if len(ihdr) != 13:
        raise CandidatePolicyError("PNG IHDR length is invalid")
    width, height, bit_depth, color_type, compression, filter_method, interlace = struct.unpack(
        ">IIBBBBB", ihdr
    )
    if (
        width < 1
        or height < 1
        or width > MAX_PNG_WIDTH
        or height > MAX_PNG_HEIGHT
        or width * height > MAX_PNG_PIXELS
    ):
        raise CandidatePolicyError("PNG dimensions exceed the closed bounds")
    legal_depths = {
        0: {1, 2, 4, 8, 16},
        2: {8, 16},
        3: {1, 2, 4, 8},
        4: {8, 16},
        6: {8, 16},
    }
    if bit_depth not in legal_depths.get(color_type, set()):
        raise CandidatePolicyError("PNG bit-depth/color-type combination is invalid")
    if compression != 0 or filter_method != 0 or interlace != 0:
        raise CandidatePolicyError("PNG must use standard compression/filtering and no interlace")

    allowed_chunks = {b"IHDR", b"PLTE", b"IDAT", b"IEND", b"sRGB", b"gAMA", b"cHRM", b"pHYs", b"tRNS", b"bKGD"}
    if any(kind in {b"acTL", b"fcTL", b"fdAT"} for kind, _ in chunks):
        raise CandidatePolicyError("APNG is not allowed")
    if any(kind not in allowed_chunks for kind, _ in chunks):
        raise CandidatePolicyError("PNG contains a non-allowlisted chunk")
    if any(sum(item_kind == kind for item_kind, _ in chunks) > 1 for kind in allowed_chunks - {b"IDAT"}):
        raise CandidatePolicyError("PNG contains duplicate singleton chunks")
    idat_positions = [index for index, (kind, _) in enumerate(chunks) if kind == b"IDAT"]
    if not idat_positions or idat_positions != list(range(idat_positions[0], idat_positions[-1] + 1)):
        raise CandidatePolicyError("PNG IDAT chunks must be present and consecutive")
    first_idat = idat_positions[0]
    if any(kind not in {b"IHDR", b"IDAT", b"IEND"} for kind, _ in chunks[first_idat + 1 :]):
        raise CandidatePolicyError("PNG ancillary chunks must precede IDAT")
    plte = next((payload for kind, payload in chunks if kind == b"PLTE"), None)
    if color_type == 3 and plte is None:
        raise CandidatePolicyError("indexed PNG is missing PLTE")
    if color_type in {0, 4} and plte is not None:
        raise CandidatePolicyError("grayscale PNG must not contain PLTE")
    if plte is not None and (len(plte) < 3 or len(plte) > 768 or len(plte) % 3 != 0):
        raise CandidatePolicyError("PNG PLTE length is invalid")
    if plte is not None and next(index for index, item in enumerate(chunks) if item[0] == b"PLTE") > first_idat:
        raise CandidatePolicyError("PNG PLTE must precede IDAT")
    chunk_positions = {kind: index for index, (kind, _) in enumerate(chunks)}
    plte_position = chunk_positions.get(b"PLTE")
    if plte_position is not None:
        if any(
            chunk_positions.get(kind, plte_position + 1) < plte_position
            for kind in {b"tRNS", b"bKGD"}
        ):
            raise CandidatePolicyError("PNG palette-dependent chunks must follow PLTE")
        if any(
            chunk_positions.get(kind, -1) > plte_position
            for kind in {b"gAMA", b"cHRM", b"sRGB"}
        ):
            raise CandidatePolicyError("PNG color-space chunks must precede PLTE")
    palette_entries = len(plte) // 3 if plte is not None else 0
    if color_type == 3 and palette_entries > 2**bit_depth:
        raise CandidatePolicyError("indexed PNG palette exceeds its bit depth")

    singleton_payloads = {kind: payload for kind, payload in chunks if kind not in {b"IDAT"}}
    transparency = singleton_payloads.get(b"tRNS")
    if transparency is not None:
        valid_transparency = (
            (color_type == 0 and len(transparency) == 2)
            or (color_type == 2 and len(transparency) == 6)
            or (color_type == 3 and 1 <= len(transparency) <= palette_entries)
        )
        if not valid_transparency:
            raise CandidatePolicyError("PNG tRNS payload is invalid for its color type")
    background = singleton_payloads.get(b"bKGD")
    if background is not None:
        expected_background_length = {0: 2, 2: 6, 3: 1, 4: 2, 6: 6}[color_type]
        if len(background) != expected_background_length or (
            color_type == 3 and background[0] >= palette_entries
        ):
            raise CandidatePolicyError("PNG bKGD payload is invalid for its color type")
    gamma = singleton_payloads.get(b"gAMA")
    if gamma is not None and (len(gamma) != 4 or gamma == b"\x00\x00\x00\x00"):
        raise CandidatePolicyError("PNG gAMA payload is invalid")
    chromaticity = singleton_payloads.get(b"cHRM")
    if chromaticity is not None and len(chromaticity) != 32:
        raise CandidatePolicyError("PNG cHRM payload is invalid")
    srgb = singleton_payloads.get(b"sRGB")
    if srgb is not None and (len(srgb) != 1 or srgb[0] > 3):
        raise CandidatePolicyError("PNG sRGB payload is invalid")
    physical = singleton_payloads.get(b"pHYs")
    if physical is not None and (len(physical) != 9 or physical[-1] not in {0, 1}):
        raise CandidatePolicyError("PNG pHYs payload is invalid")

    channels = {0: 1, 2: 3, 3: 1, 4: 2, 6: 4}[color_type]
    row_bytes = math.ceil(width * channels * bit_depth / 8)
    expected_decoded = height * (row_bytes + 1)
    compressed = b"".join(payload for kind, payload in chunks if kind == b"IDAT")
    try:
        decompressor = zlib.decompressobj()
        decoded = decompressor.decompress(compressed, expected_decoded + 1)
        remaining = expected_decoded + 1 - len(decoded)
        if remaining > 0:
            decoded += decompressor.flush(remaining)
    except zlib.error as exc:
        raise CandidatePolicyError("PNG IDAT zlib stream is invalid") from exc
    if (
        len(decoded) != expected_decoded
        or not decompressor.eof
        or decompressor.unused_data
        or decompressor.unconsumed_tail
    ):
        raise CandidatePolicyError("PNG decoded byte count is not bound to IHDR")
    stride = row_bytes + 1
    if any(decoded[index] > 4 for index in range(0, len(decoded), stride)):
        raise CandidatePolicyError("PNG contains an invalid row filter")
    return {"width": width, "height": height}


def validate_candidate_bundle(
    entries: Iterable[tuple[str, str, bytes]],
) -> dict[str, dict[str, int]]:
    materialized = list(entries)
    if not materialized or len(materialized) > MAX_FILES:
        raise CandidatePolicyError("candidate file count is outside the closed bounds")
    if sum(len(content) for _, _, content in materialized) > MAX_TOTAL_BYTES:
        raise CandidatePolicyError("candidate bundle exceeds the total byte limit")
    seen: set[str] = set()
    png_info: dict[str, dict[str, int]] = {}
    for raw_path, media_type, content in materialized:
        path = validate_safe_path(raw_path)
        folded = path.casefold()
        if folded in seen:
            raise CandidatePolicyError("candidate paths collide case-insensitively")
        seen.add(folded)
        if not isinstance(content, bytes) or not content or len(content) > MAX_FILE_BYTES:
            if isinstance(content, bytes) and not content:
                raise CandidatePolicyError(f"{path} must be non-empty")
            raise CandidatePolicyError(f"{path} exceeds the per-file byte limit")
        suffix = PurePosixPath(path).suffix.casefold()
        if suffix == ".png":
            if media_type != "image/png":
                raise CandidatePolicyError(f"{path} media type does not match PNG")
            png_info[path] = validate_png(content)
            continue
        expected_type = _TEXT_TYPES.get(suffix)
        if expected_type is None or expected_type != media_type:
            raise CandidatePolicyError(f"{path} is outside the candidate allowlist")
        _validate_text(path, media_type, content)
    return png_info
